### ISSUE TITLE
Consider contributing this to github.com/flathub

### ISSUE THREAD

**Issue by sofar** [Kekun/flatpak-minecraft#4]
See topic. I bet plenty of people would be willing to help out if this was maintained and available through flathub. As it is, only a google search finds it, but you still need a local build. On flathub, the infrastructure would do the builds.

**Comment by Kekun** [comment]
Here is what you want: https://github.com/flathub/flathub/pull/160

**Comment by sofar** [comment]
Aw, that's unfortunate :/
